name: Stroke_prediction
channels:
  - defaults

dependencies:
- python=3.10.14
- pip<=24.0
- pip:
  - mlflow==2.13.0
  - numpy==1.26.4
  - pandas==2.2.2
  - scikit-learn==1.5.0
  - scipy==1.13.1
  - xgboost==2.0.3