name: Stroke_prediction
channels:
  - defaults

dependencies:
  - python=3.10.13
  - pip<=23.2.1
  - pip:
    - alembic==1.13.1
    - aniso8601==9.0.1
    - blinker==1.8.2
    - cachetools==5.3.3
    - certifi==2024.2.2
    - charset-normalizer==3.3.2
    - click==8.1.7
    - cloudpickle==3.0.0
    - colorama==0.4.6
    - colorlog==6.8.2
    - contourpy==1.2.1
    - cycler==0.12.1
    - Deprecated==1.2.14
    - docker==7.1.0
    - entrypoints==0.4
    - Flask==3.0.3
    - fonttools==4.52.1
    - gitdb==4.0.11
    - GitPython==3.1.43
    - graphene==3.3
    - graphql-core==3.2.3
    - graphql-relay==3.2.0
    - greenlet==3.0.3
    - idna==3.7
    - importlib-metadata==7.0.0
    - itsdangerous==2.2.0
    - Jinja2==3.1.4
    - joblib==1.4.2
    - kiwisolver==1.4.5
    - Mako==1.3.5
    - Markdown==3.6
    - MarkupSafe==2.1.5
    - matplotlib==3.9.0
    - mlflow==2.13.0
    - numpy==1.26.4
    - opentelemetry-api==1.24.0
    - opentelemetry-sdk==1.24.0
    - opentelemetry-semantic-conventions==0.45b0
    - optuna==3.6.1
    - packaging==24.0
    - pandas==2.2.2
    - pillow==10.3.0
    - protobuf==4.25.3
    - pyarrow==15.0.2
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pytz==2024.1
    - pywin32==306
    - PyYAML==6.0.1
    - querystring-parser==1.2.4
    - requests==2.32.2
    - scikit-learn==1.5.0
    - scipy==1.13.1
    - six==1.16.0
    - smmap==5.0.1
    - SQLAlchemy==2.0.30
    - sqlparse==0.5.0
    - threadpoolctl==3.5.0
    - tqdm==4.66.4
    - typing_extensions==4.12.0
    - tzdata==2024.1
    - urllib3==2.2.1
    - waitress==3.0.0
    - Werkzeug==3.0.3
    - wrapt==1.16.0
    - xgboost==2.0.3
    - zipp==3.18.2- 